promise.then((result) => {
    console.log("Success", result);
}).catch((error) => {
    console.log("Error", error);
})